name: ci

on:
  push:
    branches:
      - "ci"

jobs:
  docker:
    strategy:
      matrix:
        version: ["2.6.8", "3.0.5", "3.2.0"]
        image: ["almalinux:8", "almalinux:9", "amazonlinux:2022"]
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set image tag
        run: echo IMAGE_TAG=${{ matrix.version }}-$(echo ${{ matrix.image }} | tr ':' '-') >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64
          #platforms: linux/amd64,linux/arm64
          build-args: |
            IMAGE=${{ matrix.image }}
            RUBY_VERSION=${{ matrix.version }}
          push: true
          tags: ameir/ruby:${{ env.IMAGE_TAG }}
